# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run a gradle build
        run: |
          chmod +x gradlew
          ./gradlew build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - run: 'which ssh-agent || ( apt-get install -qq openssh-client )'
      - run: eval $(ssh-agent -s)
      - run: touch private_key
      - name: ssh
        env:
          DEPLOY_SSH: ${{ secrets.DEPLOY_SSH }}
        run: echo "$PRIVATE_SSH" >> private_key
      - run: echo private_key
      - run: chmod 400 private_key
      - run: ssh -i private_key -p 22 -o StrictHostKeyChecking=no site@139.162.223.18 "./deploy2.sh"
